// UFSM BI Ganhos Economicos PI Pre-loaded Data
var initialGanhosData = [
    {
        "data":  "5/1/2018",
        "dia":  5,
        "mes":  1,
        "ano":  2018,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FATEC",
        "valor_total":  38649.53,
        "valor_ufsm":  25766.35,
        "valor_departamento":  12883.18,
        "valor_inventor":  0
    },
    {
        "data":  "10/4/2018",
        "dia":  10,
        "mes":  4,
        "ano":  2018,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FATEC",
        "valor_total":  31769.41,
        "valor_ufsm":  21179.61,
        "valor_departamento":  10589.8,
        "valor_inventor":  0
    },
    {
        "data":  "11/7/2018",
        "dia":  11,
        "mes":  7,
        "ano":  2018,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FATEC",
        "valor_total":  33368.98,
        "valor_ufsm":  22245.99,
        "valor_departamento":  11122.99,
        "valor_inventor":  0
    },
    {
        "data":  "22/8/2018",
        "dia":  22,
        "mes":  8,
        "ano":  2018,
        "descricao":  "TECNAL IND. COM. IMP. E EXP. DE EQUIP. PARA LAB LTDA",
        "departamento":  "Tecnologia e Ciência Alimentos",
        "fundacao":  "FATEC",
        "valor_total":  2700,
        "valor_ufsm":  900,
        "valor_departamento":  900,
        "valor_inventor":  900
    },
    {
        "data":  "3/10/2018",
        "dia":  3,
        "mes":  10,
        "ano":  2018,
        "descricao":  "TECNAL IND. COM. IMP. E EXP. DE EQUIP. PARA LAB LTDA",
        "departamento":  "Tecnologia e Ciência Alimentos",
        "fundacao":  "FATEC",
        "valor_total":  300,
        "valor_ufsm":  100,
        "valor_departamento":  100,
        "valor_inventor":  100
    },
    {
        "data":  "11/10/2018",
        "dia":  11,
        "mes":  10,
        "ano":  2018,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FATEC",
        "valor_total":  32711.63,
        "valor_ufsm":  21807.75,
        "valor_departamento":  10903.88,
        "valor_inventor":  0
    },
    {
        "data":  "9/1/2019",
        "dia":  9,
        "mes":  1,
        "ano":  2019,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FATEC",
        "valor_total":  36722.33,
        "valor_ufsm":  24481.55,
        "valor_departamento":  12240.78,
        "valor_inventor":  0
    },
    {
        "data":  "24/1/2019",
        "dia":  24,
        "mes":  1,
        "ano":  2019,
        "descricao":  "TECNAL IND. COM. IMP. E EXP. DE EQUIP. PARA LAB LTDA",
        "departamento":  "Tecnologia e Ciência Alimentos",
        "fundacao":  "FATEC",
        "valor_total":  2400,
        "valor_ufsm":  800,
        "valor_departamento":  800,
        "valor_inventor":  800
    },
    {
        "data":  "11/4/2019",
        "dia":  11,
        "mes":  4,
        "ano":  2019,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FATEC",
        "valor_total":  29843.78,
        "valor_ufsm":  19895.85,
        "valor_departamento":  9947.93,
        "valor_inventor":  0
    },
    {
        "data":  "11/7/2019",
        "dia":  11,
        "mes":  7,
        "ano":  2019,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FATEC",
        "valor_total":  37921.71,
        "valor_ufsm":  25281.14,
        "valor_departamento":  12640.57,
        "valor_inventor":  0
    },
    {
        "data":  "10/10/2019",
        "dia":  10,
        "mes":  10,
        "ano":  2019,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FATEC",
        "valor_total":  31356.53,
        "valor_ufsm":  20904.35,
        "valor_departamento":  10452.18,
        "valor_inventor":  0
    },
    {
        "data":  "14/10/2019",
        "dia":  14,
        "mes":  10,
        "ano":  2019,
        "descricao":  "SI Service Tecnologia da Informação Ltda",
        "departamento":  "Eng. Rural",
        "fundacao":  "FATEC",
        "valor_total":  3660.29,
        "valor_ufsm":  2440.19,
        "valor_departamento":  1220.1,
        "valor_inventor":  0
    },
    {
        "data":  "13/1/2020",
        "dia":  13,
        "mes":  1,
        "ano":  2020,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FATEC",
        "valor_total":  35430.63,
        "valor_ufsm":  23620.42,
        "valor_departamento":  11810.21,
        "valor_inventor":  0
    },
    {
        "data":  "14/1/2020",
        "dia":  14,
        "mes":  1,
        "ano":  2020,
        "descricao":  "SI Service Tecnologia da Informação Ltda",
        "departamento":  "Eng. Rural",
        "fundacao":  "FATEC",
        "valor_total":  4722.67,
        "valor_ufsm":  3148.45,
        "valor_departamento":  1574.22,
        "valor_inventor":  0
    },
    {
        "data":  "4/3/2020",
        "dia":  4,
        "mes":  3,
        "ano":  2020,
        "descricao":  "TECNAL IND. COM. IMP. E EXP. DE EQUIP. PARA LAB LTDA",
        "departamento":  "Tecnologia e Ciência Alimentos",
        "fundacao":  "FATEC",
        "valor_total":  5400,
        "valor_ufsm":  1800,
        "valor_departamento":  1800,
        "valor_inventor":  1800
    },
    {
        "data":  "27/7/2020",
        "dia":  27,
        "mes":  7,
        "ano":  2020,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FATEC",
        "valor_total":  33473.79,
        "valor_ufsm":  22315.86,
        "valor_departamento":  11157.93,
        "valor_inventor":  0
    },
    {
        "data":  "27/7/2020",
        "dia":  27,
        "mes":  7,
        "ano":  2020,
        "descricao":  "SI Service Tecnologia da Informação Ltda",
        "departamento":  "Eng. Rural",
        "fundacao":  "FATEC",
        "valor_total":  15090.15,
        "valor_ufsm":  10060.1,
        "valor_departamento":  5030.05,
        "valor_inventor":  0
    },
    {
        "data":  "10/8/2020",
        "dia":  10,
        "mes":  8,
        "ano":  2020,
        "descricao":  "SI Service Tecnologia da Informação Ltda",
        "departamento":  "Eng. Rural",
        "fundacao":  "FATEC",
        "valor_total":  664.08,
        "valor_ufsm":  442.72,
        "valor_departamento":  221.36,
        "valor_inventor":  0
    },
    {
        "data":  "28/9/2020",
        "dia":  28,
        "mes":  9,
        "ano":  2020,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FATEC",
        "valor_total":  34548.5,
        "valor_ufsm":  23032.33,
        "valor_departamento":  11516.17,
        "valor_inventor":  0
    },
    {
        "data":  "13/10/2020",
        "dia":  13,
        "mes":  10,
        "ano":  2020,
        "descricao":  "SI Service Tecnologia da Informação Ltda",
        "departamento":  "Eng. Rural",
        "fundacao":  "FATEC",
        "valor_total":  3701.04,
        "valor_ufsm":  2467.36,
        "valor_departamento":  1233.68,
        "valor_inventor":  0
    },
    {
        "data":  "25/11/2020",
        "dia":  25,
        "mes":  11,
        "ano":  2020,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FATEC",
        "valor_total":  31485.24,
        "valor_ufsm":  20990.16,
        "valor_departamento":  10495.08,
        "valor_inventor":  0
    },
    {
        "data":  "4/12/2020",
        "dia":  4,
        "mes":  12,
        "ano":  2020,
        "descricao":  "TECNAL IND. COM. IMP. E EXP. DE EQUIP. PARA LAB LTDA",
        "departamento":  "CPD",
        "fundacao":  "FATEC",
        "valor_total":  585,
        "valor_ufsm":  195,
        "valor_departamento":  195,
        "valor_inventor":  195
    },
    {
        "data":  "13/1/2021",
        "dia":  13,
        "mes":  1,
        "ano":  2021,
        "descricao":  "SI Service Tecnologia da Informação Ltda",
        "departamento":  "Eng. Rural",
        "fundacao":  "FATEC",
        "valor_total":  4121.27,
        "valor_ufsm":  2060.64,
        "valor_departamento":  2060.64,
        "valor_inventor":  0
    },
    {
        "data":  "15/1/2021",
        "dia":  15,
        "mes":  1,
        "ano":  2021,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FATEC",
        "valor_total":  31801.85,
        "valor_ufsm":  15900.93,
        "valor_departamento":  15900.93,
        "valor_inventor":  0
    },
    {
        "data":  "25/1/2021",
        "dia":  25,
        "mes":  1,
        "ano":  2021,
        "descricao":  "TECNAL IND. COM. IMP. E EXP. DE EQUIP. PARA LAB LTDA",
        "departamento":  "Tecnologia e Ciência Alimentos",
        "fundacao":  "FATEC",
        "valor_total":  4815,
        "valor_ufsm":  1605,
        "valor_departamento":  1605,
        "valor_inventor":  1605
    },
    {
        "data":  "13/4/2021",
        "dia":  13,
        "mes":  4,
        "ano":  2021,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FATEC",
        "valor_total":  33410.6,
        "valor_ufsm":  16705.3,
        "valor_departamento":  16705.3,
        "valor_inventor":  0
    },
    {
        "data":  "14/4/2021",
        "dia":  14,
        "mes":  4,
        "ano":  2021,
        "descricao":  "SI Service Tecnologia da Informação Ltda",
        "departamento":  "Eng. Rural",
        "fundacao":  "FATEC",
        "valor_total":  3587.47,
        "valor_ufsm":  1793.74,
        "valor_departamento":  1793.74,
        "valor_inventor":  0
    },
    {
        "data":  "13/7/2021",
        "dia":  13,
        "mes":  7,
        "ano":  2021,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FATEC",
        "valor_total":  34128.72,
        "valor_ufsm":  17064.36,
        "valor_departamento":  17064.36,
        "valor_inventor":  0
    },
    {
        "data":  "13/7/2021",
        "dia":  13,
        "mes":  7,
        "ano":  2021,
        "descricao":  "SI Service Tecnologia da Informação Ltda",
        "departamento":  "Eng. Rural",
        "fundacao":  "FATEC",
        "valor_total":  13150.35,
        "valor_ufsm":  6575.18,
        "valor_departamento":  6575.18,
        "valor_inventor":  0
    },
    {
        "data":  "14/7/2021",
        "dia":  14,
        "mes":  7,
        "ano":  2021,
        "descricao":  "SI Service Tecnologia da Informação Ltda",
        "departamento":  "Eng. Rural",
        "fundacao":  "FATEC",
        "valor_total":  3726.65,
        "valor_ufsm":  1863.33,
        "valor_departamento":  1863.33,
        "valor_inventor":  0
    },
    {
        "data":  "11/10/2021",
        "dia":  11,
        "mes":  10,
        "ano":  2021,
        "descricao":  "SI Service Tecnologia da Informação Ltda",
        "departamento":  "Eng. Rural",
        "fundacao":  "FATEC",
        "valor_total":  4835.21,
        "valor_ufsm":  2417.61,
        "valor_departamento":  2417.61,
        "valor_inventor":  0
    },
    {
        "data":  "13/10/2021",
        "dia":  13,
        "mes":  10,
        "ano":  2021,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FATEC",
        "valor_total":  34128.72,
        "valor_ufsm":  17064.36,
        "valor_departamento":  17064.36,
        "valor_inventor":  0
    },
    {
        "data":  "28/10/2021",
        "dia":  28,
        "mes":  10,
        "ano":  2021,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FATEC",
        "valor_total":  2335.07,
        "valor_ufsm":  1167.54,
        "valor_departamento":  1167.54,
        "valor_inventor":  0
    },
    {
        "data":  "11/11/2021",
        "dia":  11,
        "mes":  11,
        "ano":  2021,
        "descricao":  "QP Comércio Comércio e Produção de Mudas e Insumos LTDA",
        "departamento":  "Fitotecnia",
        "fundacao":  "FUNDEP",
        "valor_total":  1434.91,
        "valor_ufsm":  478.3,
        "valor_departamento":  478.3,
        "valor_inventor":  478.3
    },
    {
        "data":  "17/12/2021",
        "dia":  17,
        "mes":  12,
        "ano":  2021,
        "descricao":  "HCC– Projetos Elétricos S/A",
        "departamento":  "Engenharia de Produção e Sistemas",
        "fundacao":  "FUNDEP",
        "valor_total":  5000,
        "valor_ufsm":  1666.67,
        "valor_departamento":  1666.67,
        "valor_inventor":  1666.67
    },
    {
        "data":  "17/1/2022",
        "dia":  17,
        "mes":  1,
        "ano":  2022,
        "descricao":  "SI Service Tecnologia da Informação Ltda",
        "departamento":  "Eng. Rural",
        "fundacao":  "FATEC",
        "valor_total":  2812.16,
        "valor_ufsm":  1406.08,
        "valor_departamento":  1406.08,
        "valor_inventor":  0
    },
    {
        "data":  "26/1/2022",
        "dia":  26,
        "mes":  1,
        "ano":  2022,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FATEC",
        "valor_total":  44775.07,
        "valor_ufsm":  22387.54,
        "valor_departamento":  22387.54,
        "valor_inventor":  0
    },
    {
        "data":  "31/3/2022",
        "dia":  31,
        "mes":  3,
        "ano":  2022,
        "descricao":  "QP Comércio Comércio e Produção de Mudas e Insumos LTDA",
        "departamento":  "Fitotecnia",
        "fundacao":  "FUNDEP",
        "valor_total":  1037.13,
        "valor_ufsm":  345.71,
        "valor_departamento":  345.71,
        "valor_inventor":  345.71
    },
    {
        "data":  "12/7/2022",
        "dia":  12,
        "mes":  7,
        "ano":  2022,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FATEC",
        "valor_total":  48762.27,
        "valor_ufsm":  24381.14,
        "valor_departamento":  24381.14,
        "valor_inventor":  0
    },
    {
        "data":  "18/7/2022",
        "dia":  18,
        "mes":  7,
        "ano":  2022,
        "descricao":  "SI Service Tecnologia da Informação Ltda",
        "departamento":  "Eng. Rural",
        "fundacao":  "FATEC",
        "valor_total":  9311.78,
        "valor_ufsm":  4655.89,
        "valor_departamento":  4655.89,
        "valor_inventor":  0
    },
    {
        "data":  "14/10/2022",
        "dia":  14,
        "mes":  10,
        "ano":  2022,
        "descricao":  "QP Comércio Comércio e Produção de Mudas e Insumos LTDA",
        "departamento":  "Fitotecnia",
        "fundacao":  "FUNDEP",
        "valor_total":  2229.48,
        "valor_ufsm":  743.16,
        "valor_departamento":  743.16,
        "valor_inventor":  743.16
    },
    {
        "data":  "18/10/2022",
        "dia":  18,
        "mes":  10,
        "ano":  2022,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FATEC",
        "valor_total":  51536.81,
        "valor_ufsm":  25768.41,
        "valor_departamento":  25768.41,
        "valor_inventor":  0
    },
    {
        "data":  "4/11/2022",
        "dia":  4,
        "mes":  11,
        "ano":  2022,
        "descricao":  "SI Service Tecnologia da Informação Ltda",
        "departamento":  "Eng. Rural",
        "fundacao":  "FATEC",
        "valor_total":  1801.97,
        "valor_ufsm":  900.99,
        "valor_departamento":  900.99,
        "valor_inventor":  0
    },
    {
        "data":  "8/3/2023",
        "dia":  8,
        "mes":  3,
        "ano":  2023,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  47100.57,
        "valor_ufsm":  21195.26,
        "valor_departamento":  21195.26,
        "valor_inventor":  0
    },
    {
        "data":  "8/3/2023",
        "dia":  8,
        "mes":  3,
        "ano":  2023,
        "descricao":  "Huawei do Brasil Telecomunicações",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  108631,
        "valor_ufsm":  32589.3,
        "valor_departamento":  32589.3,
        "valor_inventor":  32589.3
    },
    {
        "data":  "10/4/2023",
        "dia":  10,
        "mes":  4,
        "ano":  2023,
        "descricao":  "QP Comércio Comércio e Produção de Mudas e Insumos LTDA",
        "departamento":  "Fitotecnia",
        "fundacao":  "FUNDEP",
        "valor_total":  538.26,
        "valor_ufsm":  179.42,
        "valor_departamento":  179.42,
        "valor_inventor":  179.42
    },
    {
        "data":  "2/5/2023",
        "dia":  2,
        "mes":  5,
        "ano":  2023,
        "descricao":  "SI Service Tecnologia da Informação Ltda",
        "departamento":  "Eng. Rural",
        "fundacao":  "FUNDEP",
        "valor_total":  143.99,
        "valor_ufsm":  72,
        "valor_departamento":  72,
        "valor_inventor":  0
    },
    {
        "data":  "24/4/2023",
        "dia":  24,
        "mes":  4,
        "ano":  2023,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  52543.84,
        "valor_ufsm":  23644.73,
        "valor_departamento":  23644.73,
        "valor_inventor":  0
    },
    {
        "data":  "21/7/2023",
        "dia":  21,
        "mes":  7,
        "ano":  2023,
        "descricao":  "SI Service Tecnologia da Informação Ltda",
        "departamento":  "Eng. Rural",
        "fundacao":  "FUNDEP",
        "valor_total":  327.8,
        "valor_ufsm":  163.9,
        "valor_departamento":  163.9,
        "valor_inventor":  0
    },
    {
        "data":  "25/7/2023",
        "dia":  25,
        "mes":  7,
        "ano":  2023,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  51182.72,
        "valor_ufsm":  23032.22,
        "valor_departamento":  23032.22,
        "valor_inventor":  0
    },
    {
        "data":  "18/9/2023",
        "dia":  18,
        "mes":  9,
        "ano":  2023,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  17098.6,
        "valor_ufsm":  7694.37,
        "valor_departamento":  7694.37,
        "valor_inventor":  0
    },
    {
        "data":  "5/10/2023",
        "dia":  5,
        "mes":  10,
        "ano":  2023,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  17301.92,
        "valor_ufsm":  7785.86,
        "valor_departamento":  7785.86,
        "valor_inventor":  0
    },
    {
        "data":  "6/11/2023",
        "dia":  6,
        "mes":  11,
        "ano":  2023,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  17421.92,
        "valor_ufsm":  7839.86,
        "valor_departamento":  7839.86,
        "valor_inventor":  0
    },
    {
        "data":  "5/12/2023",
        "dia":  5,
        "mes":  12,
        "ano":  2023,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  24801.92,
        "valor_ufsm":  11160.86,
        "valor_departamento":  11160.86,
        "valor_inventor":  0
    },
    {
        "data":  "5/12/2023",
        "dia":  5,
        "mes":  12,
        "ano":  2023,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  39000,
        "valor_ufsm":  17550,
        "valor_departamento":  17550,
        "valor_inventor":  0
    },
    {
        "data":  "2/1/2024",
        "dia":  2,
        "mes":  1,
        "ano":  2024,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  18757.77,
        "valor_ufsm":  8441,
        "valor_departamento":  8441,
        "valor_inventor":  0
    },
    {
        "data":  "9/2/2024",
        "dia":  9,
        "mes":  2,
        "ano":  2024,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  20396.38,
        "valor_ufsm":  9178.37,
        "valor_departamento":  9178.37,
        "valor_inventor":  0
    },
    {
        "data":  "15/1/2024",
        "dia":  15,
        "mes":  1,
        "ano":  2024,
        "descricao":  "Auftek",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  2555.9,
        "valor_ufsm":  766.77,
        "valor_departamento":  766.77,
        "valor_inventor":  766.77
    },
    {
        "data":  "9/2/2024",
        "dia":  9,
        "mes":  2,
        "ano":  2024,
        "descricao":  "QP Comércio Comércio e Produção de Mudas e Insumos LTDA",
        "departamento":  "Fitotecnia",
        "fundacao":  "FUNDEP",
        "valor_total":  1075.98,
        "valor_ufsm":  358.66,
        "valor_departamento":  358.66,
        "valor_inventor":  0
    },
    {
        "data":  "13/3/2024",
        "dia":  13,
        "mes":  3,
        "ano":  2024,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  20493.32,
        "valor_ufsm":  9221.99,
        "valor_departamento":  9221.99,
        "valor_inventor":  0
    },
    {
        "data":  "27/3/2024",
        "dia":  27,
        "mes":  3,
        "ano":  2024,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  22052.14,
        "valor_ufsm":  9923.46,
        "valor_departamento":  9923.46,
        "valor_inventor":  0
    },
    {
        "data":  "7/5/2024",
        "dia":  7,
        "mes":  5,
        "ano":  2024,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  19829.51,
        "valor_ufsm":  8923.28,
        "valor_departamento":  8923.28,
        "valor_inventor":  0
    },
    {
        "data":  "03/06/24",
        "dia":  3,
        "mes":  6,
        "ano":  2024,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  19829.51,
        "valor_ufsm":  8923.28,
        "valor_departamento":  8923.28,
        "valor_inventor":  0
    },
    {
        "data":  "27/06/24",
        "dia":  27,
        "mes":  6,
        "ano":  2024,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  19829.51,
        "valor_ufsm":  8923.28,
        "valor_departamento":  8923.28,
        "valor_inventor":  0
    },
    {
        "data":  "20/02/24",
        "dia":  20,
        "mes":  2,
        "ano":  2024,
        "descricao":  "Luiz Alfredo Dittgen Miritz – ME nome fantasia “Som Maior Proaudio”",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  864,
        "valor_ufsm":  259.2,
        "valor_departamento":  259.2,
        "valor_inventor":  259.2
    },
    {
        "data":  "01/08/24",
        "dia":  1,
        "mes":  8,
        "ano":  2024,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  19829.51,
        "valor_ufsm":  8923.28,
        "valor_departamento":  8923.28,
        "valor_inventor":  0
    },
    {
        "data":  "02/09/24",
        "dia":  2,
        "mes":  9,
        "ano":  2024,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  19829.51,
        "valor_ufsm":  8923.28,
        "valor_departamento":  8923.28,
        "valor_inventor":  0
    },
    {
        "data":  "02/10/24",
        "dia":  2,
        "mes":  10,
        "ano":  2024,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  17398.74,
        "valor_ufsm":  7829.43,
        "valor_departamento":  7829.43,
        "valor_inventor":  0
    },
    {
        "data":  "01/11/24",
        "dia":  1,
        "mes":  11,
        "ano":  2024,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  18422.91,
        "valor_ufsm":  8290.31,
        "valor_departamento":  8290.31,
        "valor_inventor":  0
    },
    {
        "data":  "28/11/24",
        "dia":  28,
        "mes":  11,
        "ano":  2024,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  18896.29,
        "valor_ufsm":  8503.33,
        "valor_departamento":  8503.33,
        "valor_inventor":  0
    },
    {
        "data":  "14/10/24",
        "dia":  14,
        "mes":  10,
        "ano":  2024,
        "descricao":  "Auftek",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  650,
        "valor_ufsm":  195,
        "valor_departamento":  195,
        "valor_inventor":  195
    },
    {
        "data":  "20/11/24",
        "dia":  20,
        "mes":  11,
        "ano":  2024,
        "descricao":  "INGAL",
        "departamento":  "",
        "fundacao":  "FUNDEP",
        "valor_total":  204.68,
        "valor_ufsm":  61.4,
        "valor_departamento":  61.4,
        "valor_inventor":  61.4
    },
    {
        "data":  "20/11/24",
        "dia":  20,
        "mes":  11,
        "ano":  2024,
        "descricao":  "INGAL",
        "departamento":  "",
        "fundacao":  "FUNDEP",
        "valor_total":  1333.62,
        "valor_ufsm":  400.09,
        "valor_departamento":  400.09,
        "valor_inventor":  400.09
    },
    {
        "data":  "06/01/25",
        "dia":  6,
        "mes":  1,
        "ano":  2025,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  18989.72,
        "valor_ufsm":  8545.37,
        "valor_departamento":  8545.37,
        "valor_inventor":  0
    },
    {
        "data":  "19/12/24",
        "dia":  19,
        "mes":  12,
        "ano":  2024,
        "descricao":  "QP Comércio Comércio e Produção de Mudas e Insumos LTDA",
        "departamento":  "",
        "fundacao":  "FUNDEP",
        "valor_total":  2164.91,
        "valor_ufsm":  649.47,
        "valor_departamento":  649.47,
        "valor_inventor":  649.47
    },
    {
        "data":  "20/01/25",
        "dia":  20,
        "mes":  1,
        "ano":  2025,
        "descricao":  "Auftek",
        "departamento":  "",
        "fundacao":  "FUNDEP",
        "valor_total":  1664,
        "valor_ufsm":  499.2,
        "valor_departamento":  499.2,
        "valor_inventor":  499.2
    },
    {
        "data":  "20/01/25",
        "dia":  20,
        "mes":  1,
        "ano":  2025,
        "descricao":  "INGAL",
        "departamento":  "",
        "fundacao":  "FUNDEP",
        "valor_total":  13497.59,
        "valor_ufsm":  4049.28,
        "valor_departamento":  4049.28,
        "valor_inventor":  4049.28
    },
    {
        "data":  "20/01/25",
        "dia":  20,
        "mes":  1,
        "ano":  2025,
        "descricao":  "Agência de Desenvolvimento do Médio Alto Uruguai (ADMAU)",
        "departamento":  "",
        "fundacao":  "FUNDEP",
        "valor_total":  5237.61,
        "valor_ufsm":  1571.28,
        "valor_departamento":  1571.28,
        "valor_inventor":  1571.28
    },
    {
        "data":  "29/01/25",
        "dia":  29,
        "mes":  1,
        "ano":  2025,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  19078.41,
        "valor_ufsm":  8585.28,
        "valor_departamento":  8585.28,
        "valor_inventor":  0
    },
    {
        "data":  "28/02/25",
        "dia":  28,
        "mes":  2,
        "ano":  2025,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  19151.6,
        "valor_ufsm":  8618.22,
        "valor_departamento":  8618.22,
        "valor_inventor":  0
    },
    {
        "data":  "01/03/25",
        "dia":  1,
        "mes":  3,
        "ano":  2025,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  19203.11,
        "valor_ufsm":  8641.4,
        "valor_departamento":  8641.4,
        "valor_inventor":  0
    },
    {
        "data":  "19/03/25",
        "dia":  19,
        "mes":  3,
        "ano":  2025,
        "descricao":  "QP Comércio Comércio e Produção de Mudas e Insumos LTDA",
        "departamento":  "",
        "fundacao":  "FUNDEP",
        "valor_total":  120.8,
        "valor_ufsm":  36.24,
        "valor_departamento":  36.24,
        "valor_inventor":  36.24
    },
    {
        "data":  "20/02/24",
        "dia":  20,
        "mes":  2,
        "ano":  2024,
        "descricao":  "Luiz Alfredo Dittgen Miritz – ME nome fantasia “Som Maior Proaudio”",
        "departamento":  "",
        "fundacao":  "FUNDEP",
        "valor_total":  432,
        "valor_ufsm":  129.6,
        "valor_departamento":  129.6,
        "valor_inventor":  129.6
    },
    {
        "data":  "08/04/25",
        "dia":  8,
        "mes":  4,
        "ano":  2025,
        "descricao":  "Auftek",
        "departamento":  "",
        "fundacao":  "FUNDEP",
        "valor_total":  832,
        "valor_ufsm":  249.6,
        "valor_departamento":  249.6,
        "valor_inventor":  249.6
    },
    {
        "data":  "11/02/25",
        "dia":  11,
        "mes":  2,
        "ano":  2025,
        "descricao":  "Tecnal Industria, Comercio, Importação e Exportação de Equipamentos para Laboratório Ltda",
        "departamento":  "",
        "fundacao":  "FUNDEP",
        "valor_total":  1022.07,
        "valor_ufsm":  306.62,
        "valor_departamento":  306.62,
        "valor_inventor":  306.62
    },
    {
        "data":  "08/04/25",
        "dia":  8,
        "mes":  4,
        "ano":  2025,
        "descricao":  "INGAL",
        "departamento":  "",
        "fundacao":  "FUNDEP",
        "valor_total":  7995.42,
        "valor_ufsm":  2398.63,
        "valor_departamento":  2398.63,
        "valor_inventor":  2398.63
    },
    {
        "data":  "5/5/2025",
        "dia":  5,
        "mes":  5,
        "ano":  2025,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  18656.09,
        "valor_ufsm":  8395.24,
        "valor_departamento":  8395.24,
        "valor_inventor":  0
    },
    {
        "data":  "6/5/2025",
        "dia":  6,
        "mes":  5,
        "ano":  2025,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  16650.34,
        "valor_ufsm":  7492.65,
        "valor_departamento":  7492.65,
        "valor_inventor":  0
    },
    {
        "data":  "6/30/2025",
        "dia":  30,
        "mes":  6,
        "ano":  2025,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  20148.18,
        "valor_ufsm":  9066.68,
        "valor_departamento":  9066.68,
        "valor_inventor":  0
    },
    {
        "data":  "8/12/2025",
        "dia":  8,
        "mes":  12,
        "ano":  2025,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  20148.18,
        "valor_ufsm":  9066.68,
        "valor_departamento":  9066.68,
        "valor_inventor":  0
    },
    {
        "data":  "9/5/2025",
        "dia":  9,
        "mes":  5,
        "ano":  2025,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  19894.5,
        "valor_ufsm":  8952.53,
        "valor_departamento":  8952.53,
        "valor_inventor":  0
    },
    {
        "data":  "10/7/2025",
        "dia":  10,
        "mes":  7,
        "ano":  2025,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  21287.92,
        "valor_ufsm":  9579.56,
        "valor_departamento":  9579.56,
        "valor_inventor":  0
    },
    {
        "data":  "11/10/2025",
        "dia":  11,
        "mes":  10,
        "ano":  2025,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  21226.42,
        "valor_ufsm":  9551.89,
        "valor_departamento":  9551.89,
        "valor_inventor":  0
    },
    {
        "data":  "4/17/2025",
        "dia":  17,
        "mes":  4,
        "ano":  2025,
        "descricao":  "Luiz Alfredo Dittgen Miritz – ME nome fantasia “Som Maior Proaudio”",
        "departamento":  "",
        "fundacao":  "FUNDEP",
        "valor_total":  432,
        "valor_ufsm":  129.6,
        "valor_departamento":  129.6,
        "valor_inventor":  129.6
    },
    {
        "data":  "8/5/2025",
        "dia":  8,
        "mes":  5,
        "ano":  2025,
        "descricao":  "Auftek",
        "departamento":  "",
        "fundacao":  "FUNDEP",
        "valor_total":  1123.2,
        "valor_ufsm":  374.4,
        "valor_departamento":  374.4,
        "valor_inventor":  374.4
    },
    {
        "data":  "7/21/2025",
        "dia":  21,
        "mes":  7,
        "ano":  2025,
        "descricao":  "INGAL",
        "departamento":  "",
        "fundacao":  "FUNDEP",
        "valor_total":  466.1,
        "valor_ufsm":  139.83,
        "valor_departamento":  139.83,
        "valor_inventor":  139.83
    },
    {
        "data":  "9/5/2025",
        "dia":  9,
        "mes":  5,
        "ano":  2025,
        "descricao":  "INGAL",
        "departamento":  "",
        "fundacao":  "FUNDEP",
        "valor_total":  19927.69,
        "valor_ufsm":  5978.31,
        "valor_departamento":  5978.31,
        "valor_inventor":  5978.31
    },
    {
        "data":  "9/16/2025",
        "dia":  16,
        "mes":  9,
        "ano":  2025,
        "descricao":  "BioDos",
        "departamento":  "",
        "fundacao":  "FUNDEP",
        "valor_total":  1981.8,
        "valor_ufsm":  594.54,
        "valor_departamento":  594.54,
        "valor_inventor":  594.54
    },
    {
        "data":  "11/18/2025",
        "dia":  18,
        "mes":  11,
        "ano":  2025,
        "descricao":  "INGAL",
        "departamento":  "",
        "fundacao":  "FUNDEP",
        "valor_total":  3590.86,
        "valor_ufsm":  1077.26,
        "valor_departamento":  1077.26,
        "valor_inventor":  1077.26
    },
    {
        "data":  "6/16/2026",
        "dia":  16,
        "mes":  6,
        "ano":  2026,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  21226.42,
        "valor_ufsm":  9551.89,
        "valor_departamento":  9551.89,
        "valor_inventor":  0
    },
    {
        "data":  "6/17/2026",
        "dia":  17,
        "mes":  6,
        "ano":  2026,
        "descricao":  "AVMB - Consultoria e Assessoria em Informática Ltda.",
        "departamento":  "CPD",
        "fundacao":  "FUNDEP",
        "valor_total":  40000,
        "valor_ufsm":  9551.89,
        "valor_departamento":  9551.89,
        "valor_inventor":  0
    }
];